name: format

on:
  - push
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global pnpm
      - run: pnpm install
      - run: pnpm run format::check
